name: shelf_router_extensions_generator
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.1.1
  build_config: ^1.0.0
  source_gen: ^1.1.1
  analyzer: ^2.6.0
  shelf_router: ^1.1.1
  code_builder: ^4.1.0
  meta: ^1.7.0
  http_methods: ^1.1.0
  shelf_router_extensions:
    git:
      url: https://github.com/radzish/shelf_router_extensions.git
      path: extensions

dev_dependencies:
  test: ^1.18.2
  http: ^0.13.4
  build_verify: ^2.0.0
  build_runner: ^2.1.4
  pedantic: ^1.11.1

dependency_overrides:
  shelf_router_extensions:
    path: ../extensions
