name: shelf_router_extensions
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.2.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.18.2
