name: shelf_router_extensions_built_value_example
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf_router_extensions:
    git:
      url: https://github.com/radzish/shelf_router_extensions.git
      path: extensions

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.18.2
  build_runner: ^2.1.4
  built_value_generator: ^8.1.2
  shelf_router_extensions_generator:
    git:
      url: https://github.com/radzish/shelf_router_extensions.git
      path: generator

dependency_overrides:
  shelf_router_extensions:
    path: ../extensions
  shelf_router_extensions_generator:
    path: ../generator
